version: '3'
services:
  theywhiteboardedme:
    build: .
    volumes:
     - .:/site
    working_dir: /site
    command: "/bin/bash -c 'jekyll serve --source /site --destination /site/_site'"
    ports:
     - "4000:4000"
